CREATE DATABASE IF NOT EXISTS SCHOOL;

USE SCHOOL;

CREATE TABLE IF NOT EXISTS TEACHER(
ROLLNO INT  PRIMARY KEY,
NAME VARCHAR (20),
MARKS  INT NOT NULL,
GRADE VARCHAR (10),
CITY  VARCHAR(20)
);


INSERT INTO TEACHER
VALUES
(01 , "PARAS" , 52 , "A" , "GIDDARBAHA"),
(02 , "anu" , 42 , "b" , "malout"),
(03 , "manoj" , 92 , "b" , "bathinda"),
(04 , "sunil" , 43 , "c" , "mansa"),
(05 , "pankaj" , 23 , "b" , "mansa");


SELECT * FROM TEACHER ORDER BY CITY ASC;     -- ORDER BY IS USED TO SORT IN ASCENDING OR DESCENDING
--  OREDR BY USING CITY , NAME , ROLLNO ANYTHING ...


SELECT * FROM TEACHER ORDER BY NAME ASC;

SELECT * FROM TEACHER ORDER BY NAME DESC;   -- FOR DESCENDING OREDR BY USE ORDER BY DESC.....

SELECT * FROM TEACHER ORDER BY MARKS ASC LIMIT 3; 

