CREATE DATABASE IF NOT EXISTS SCHOOL;

USE SCHOOL;


CREATE TABLE IF NOT EXISTS TEACHER(
ROLLNO INT  PRIMARY KEY,
NAME VARCHAR (20),
MARKS  INT NOT NULL,
GRADE VARCHAR (10),
CITY  VARCHAR(20)
);


INSERT INTO TEACHER
VALUES
(01 , "PARAS" , 52 , "A" , "GIDDARBAHA"),
(02 , "PINKI" , 98 , "A" , "GIDDARBAHA"),
(03 , "SHANTI" , 12 , "A" , "GIDDARBAHA"),
(04 , "anu" , 42 , "b" , "malout"),
(05 , "manoj" , 92 , "b" , "bathinda"),
(06 , "sunil" , 43 , "c" , "mansa"),
(07 , "pankaj" , 23 , "b" , "mansa");



# Using of aggregate functions ....


SELECT MAX(MARKS) FROM TEACHER ;

SELECT MIN(MARKS) FROM TEACHER;

SELECT SUM(MARKS) FROM TEACHER;

SELECT COUNT(NAME) FROM TEACHER;

SELECT AVG(MARKS) FROM TEACHER;

                      #         GROUP BY ->

SELECT CITY, COUNT(NAME)  FROM TEACHER GROUP BY CITY;  -- GROUP BY IS USED TO TAKE DATA IN FORM 
-- OF GROUP COUNT HOW MANY STUDENTS ARE THERE IN DIFFERENT DIFFERENT CITIES ...

SELECT NAME , CITY, COUNT(MARKS) FROM TEACHER GROUP BY  NAME , CITY ;

SELECT CITY , AVG(MARKS) FROM TEACHER GROUP BY CITY;  -- GET AVERAGE MARKS OF EVERY CITY ....

-- > THIS QUERIES GIVE ME ALL CITY AVERAGE MARKS IN ASCENDING ORDER IT GIVE BY DEFAULT IN ASCENDING ORDER..

SELECT CITY , AVG(MARKS) 
 FROM TEACHER 
 GROUP BY  CITY ORDER BY AVG(MARKS);  
 
 
SELECT CITY, COUNT(NAME)
FROM TEACHER
GROUP BY CITY
HAVING MAX(MARKS) > 90;


                  -- > General order to write claues...
 SELECT CITY
 FROM TEACHER 
 WHERE GRADE = "b"
 GROUP BY CITY
 HAVING MAX(MARKS)>40
 ORDER BY CITY ASC;
