CREATE DATABASE IF NOT EXISTS SCHOOL;

USE SCHOOL;


CREATE TABLE IF NOT EXISTS TEACHER(
ROLLNO INT  PRIMARY KEY,
NAME VARCHAR (20),
MARKS  INT NOT NULL,
GRADE VARCHAR (10),
CITY  VARCHAR(20)
);


INSERT INTO TEACHER
VALUES
(01 , "PARAS" , 52 , "A" , "GIDDARBAHA"),
(02 , "PINKI" , 98 , "A" , "GIDDARBAHA"),
(03 , "SHANTI" , 12 , "A" , "GIDDARBAHA"),
(04 , "anu" , 42 , "b" , "malout"),
(05 , "manoj" , 92 , "b" , "bathinda"),
(06 , "sunil" , 43 , "c" , "mansa"),
(07 , "pankaj" , 23 , "b" , "mansa");

 
 SET SQL_SAFE_UPDATES=0;   -- > COMMAND TO TURN OFF SAFE MODE IN SQL .....
 
UPDATE TEACHER
SET CITY = "BANGALORE"
WHERE ROLLNO = 07;
 
 
 UPDATE TEACHER          -- > COMMAND FOR UPDATE IN TABLE ....
 SET GRADE = "A"
 WHERE MARKS BETWEEN 50 AND 80;
 
 
 DELETE FROM TEACHER            -- > COMMAND TO PERFORM DELETE FUNCTION IN TABLE ....
 WHERE NAME = "PANKAJ" OR NAME = "sunil";
 
 SELECT * FROM TEACHER;