CREATE DATABASE COLLEGE;

USE COLLEGE;


CREATE TABLE DEPARTMENT(
ID INT PRIMARY KEY,
NAME VARCHAR(20)
); 

INSERT INTO DEPARTMENT
VALUES 
(101 ,"Science"),
(102 ,"hindi"),
(103 ,"maths");

CREATE TABLE TEACHER(
ID INT PRIMARY KEY,
NAME VARCHAR (20),
 DEPT_ID INT , 
 FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID)  -- > USING FOREIGN KEY 
);

INSERT INTO TEACHER
VALUES
(101 , "ADAM" , 101 ),
(102, "BOB" , 103),
(103, "CASSY" , 102),
(104, "DONALD" , 102);

SELECT * FROM TEACHER;