CREATE DATABASE IF NOT EXISTS COLLEGE;

USE COLLEGE;

CREATE TABLE IF NOT EXISTS STUDENT(
ROLLNO INT  PRIMARY KEY,
NAME VARCHAR (20),
MARKS  INT NOT NULL,
GRADE VARCHAR (10),
CITY  VARCHAR(20)
);


INSERT INTO STUDENT
VALUES
(01 , "PARAS" , 52 , "A" , "GIDDARBAHA"),
(02 , "anu" , 42 , "b" , "malout"),
(03 , "manoj" , 92 , "b" , "bathinda"),
(04 , "sunil" , 43 , "c" , "mansa"),
(05 , "pankaj" , 23 , "b" , "mansa");


# select commands which we can used in our SQL PROGRAM .....


SELECT * FROM STUDENT;
SELECT ROLLNO FROM STUDENT;    -- WE can also use select to select and column from table .....
SELECT ROLLNO  , CITY FROM STUDENT;    -- SELECT multiple column at same time....

SELECT DISTINCT CITY FROM STUDENT;    -- It remove duplicate cities only show unique ....

SELECT * FROM STUDENT WHERE MARKS>50;    -- USE OF WHERE CLAUSE IN SELECT ....

SELECT * FROM STUDENT WHERE MARKS+10 > 30;   -- USE OF ARITHMATIC OPERATOR IN SELECT...

SELECT * FROM STUDENT WHERE MARKS = 23;      -- THIS BOTH ARE COMARISION OPERATOR ....
SELECT * FROM STUDENT WHERE MARKS != 23;

SELECT * FROM STUDENT WHERE MARKS BETWEEN 40 AND 100;   -- USE BETWEEN OPERATOR TO SEARCH FROM GIVEN RANGE..

SELECT * FROM STUDENT WHERE CITY IN ("GDB" , "MALOUT" , "DELHI" , "BATHINDA");  -- IN operator is used to search from 
 -- given list if some one match than give output ....
 
 SELECT * FROM STUDENT WHERE CITY NOT IN ("GDB" , "MALOUT" , "DELHI" , "BATHINDA"); -- NOT IN OPERATOR GIVE US ALL CITY
 -- WITHOUT THIS WHICH ARE WRITEEN INSIDE ...
 
 SELECT * FROM STUDENT LIMIT 2; --  NOW IT SHOW ONLY TWO ROWS LIMIT IS USED TO SET LIMIT ON ROWS ...
 
 
         #  NOW FIND ONLY 3 STUDENT FROM WHOLE TABLE WHOSE MARKS ARE GREATER THAN 40...
 
 SELECT * FROM STUDENT WHERE MARKS>40 LIMIT 3;


 
